<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Entity\CargoTrack.Entity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\AboutDtos\CargoDto\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
